pipeline {
    agent {
        kubernetes {
          yamlFile 'deploy/agent-pod.yaml'
          podRetention onFailure()
        }
    }

    stages {
        stage('Deploy') {
            environment {
                env_ = 'dev'
                namespace = 'apps'
            }

            steps {
                container('kustomize') {
                    sh """
                        cd deploy/manifests
                        kustomize build overlays/${env_} | kubectl apply -n ${namespace} --record -f -
                    """
                } 
            }
        }
    }

    post {
        always {
            notifyBuild(currentBuild.currentResult)
            echo "Finished"
        }
    }
}

def notifyBuild(String buildStatus = 'STARTED') {
    def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
    def summary = "${subject} (${env.BUILD_URL})"
    def details = """<p>${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
    <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>"""

    emailext (
        subject: subject,
        body: details,
        recipientProviders: [[$class: 'DevelopersRecipientProvider']]
    )
}
